### PR TITLE
Implement AuthenticationCleartextPassword

### PR DESCRIPTION
**Pull request by astiob**
Hit this in a real project.

NB: I’ve done my best to compare this to the docs and [PgJDBC](https://github.com/pgjdbc/pgjdbc/blob/06cecbb00f4babb455303d0330e995095f70d59d/pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java#L675-L695), but I must admit I have not tested this (yet) beyond the fact that it compiles. Ideally this would have a test right within the Skunk repo, but I’m not sure how to do it.

### CODE REVIEW

**Comment by tpolecat** [comment]
Oh cool, thanks. To test this we need to add another instance to the docker-compose setup that's configured to use cleartext passwords. Also need to update doc. I'm going to switch this to a draft PR until those things are done. If you'd like to give it a shot, look at the authentication tests and give me a heads-up. Otherwise I'll get to it at some point.

**Comment by tpolecat** [comment]
This looks great, thanks!

**Comment by tpolecat** [comment]
Please punch "ready for review" when you're happy with it.

**Comment by astiob** [comment]
I’ve re-pushed with documentation fixes (somehow I had missed the fact this was documented at all, sorry!) and with a tests in a separate commit, based on the existing ones.

I saw the earlier CI run fail, but I think it shouldn’t have been caused by the auth changes.

**Comment by astiob** [comment]
Aha, now I think it failed because it was specifically checking that cleartext wasn’t supported. I’ve removed that and re-pushed.

**Pull request merged**
