### PR TITLE
Session: add List[SocketOption] as param

### PR DESCRIPTION
**Pull request by agustafson**
We're having issues similar to #524, and thought that setting the keep-alive socket option might help to resolve that issue. This PR exposes the socket options as a param in `Session`.

### CODE REVIEW

**Comment by agustafson** [comment]
FYI tested it out and adding `SocketOption.keepAlive(true)` didn't seem to solve the underlying `BrokenPipe` issue. Think this PR might still be useful.

**Comment by hnaderi** [comment]
@agustafson Can you describe the situation which this issue occurs? does it happen locally or on deployment?
Do you maintain long lived connections?
Is your deployment on docker swarm, k8s , ...?

**Comment by mpilquist** [comment]
Thanks!

**Comment by mpilquist** [comment]
Thanks!

**Pull request merged**
