### PR TITLE
feat: added CreateRole command completion

### PR DESCRIPTION
**Pull request by joeyhage**

### CODE REVIEW

**Comment by joeyhage** [comment]
@tpolecat bump. TYIA

**Comment by joeyhage** [comment]
@tpolecat is this project still being maintained?

**Comment by joeyhage** [comment]
@mpilquist saw that you are a maintainer now - this should be a very straightforward PR. Thanks in advance for your time!

**Comment by mpilquist** [comment]
Looks good, thanks! Is there any way to add some test coverage?

**Comment by joeyhage** [comment]
@mpilquist I was rebasing and reset my fork to the main branch so GH auto closed the PR. New PR with test coverage is here: https://github.com/tpolecat/skunk/pull/714. Thank you!

**Pull request closed without merging**
