### PR TITLE
Reenable http4s

### PR DESCRIPTION
**Pull request by m-sp**
fixes https://github.com/tpolecat/skunk/issues/401

### CODE REVIEW

**Comment by tpolecat** [comment]
Hey that was fast, thanks!

**Comment by m-sp** [comment]
ugh seems like a nasty circe eviction, http4s depends on the milestone already :( any advice how to fix it?

**Comment by tpolecat** [comment]
Hang on I'll have a look.

**Comment by tpolecat** [comment]
Kind of sucks because that circe release didn't publish for Scala 3.0.0-M3.

**Comment by m-sp** [comment]
yep rather unfortunate that circe milestones only publish for one Scala version... I can revisit a bit later

**Comment by tpolecat** [comment]
Yeah http4s milestone is also only out for Scala 3..0.0-RC1.

**Comment by tpolecat** [comment]
There's kind of a cascade of things that will need fixing here, so I'm closing this one for now.

I think what we need to do first is get all of `master` building for Scala 3 (circe module and http4s example) and drop the Scala 3.0.0-M3 cross-build. Then once that's merged create a branch from series/0.1, merge master into it, and use that as the basis for getting it all working here.

**Comment by tpolecat** [comment]
An added note here, Circe 0.14 is going to break bincompat, so we can't really force people to upgrade because other things (like http4s 0.21) are depending on 0.13. So I think we don't have a move at the moment.

**Pull request closed without merging**
