### PR TITLE
More efficiently discard inputs to void

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by tpolecat** [comment]
Uh, how does that work? I haven't seen that one before.

**Comment by dwijnand** [comment]
Deprecated parameters are exempt by the lint warning.

**Comment by dwijnand** [comment]
This change isn't necessary, I just wanted to share.

I'm proposing this function to the standard library.  I'm also proposing `@unused` as an alternative to `@deprecated("unused", "")`.

In experimenting I found out you can remove your need for this function in `StringContextOps` by replacing `void(sc)` with `val _ sc`.  Again, JFYI :)

**Comment by tpolecat** [comment]
It's a good trick to know, thanks!

**Pull request closed without merging**
