### PR TITLE
Upgrade to lastest fs2 snapshot

### PR DESCRIPTION
**Pull request by mpilquist**
Draft until there's a version published, but I thought it might be good to see https://github.com/typelevel/fs2/pull/2209 in action.

### CODE REVIEW

**Comment by tpolecat** [comment]
Oh cool! This is excellent.

**Comment by mpilquist** [comment]
Do you have any concerns about dropping the read/write timeouts? Also, I was conservative here and didn't propagate ip4s types through all of Skunk internals.

**Comment by tpolecat** [comment]
I think effect timeouts are what I want, so yes this all seems good to me, although it's probably possible to get the session into an inconsistent state by doing this so it will require some testing.

**Comment by keynmol** [comment]
I didn't check for existing PRs and did the same thing (for M9), apart from propagating the Temporal effect (and updating lots of versions): https://github.com/tpolecat/skunk/compare/ce3...keynmol:ce3-latest?expand=1

(been testing it with locally published https://github.com/tpolecat/natchez/pull/272) 

@mpilquist if you intend to track this until latest fs2 is released, I can abandon my efforts and just watch this PR :)

**Comment by mpilquist** [comment]
@keynmol I had basically given up on this PR as a result of the errors from SBT about conflicting versions.

**Comment by keynmol** [comment]
Cool, I'll continue iterating on it then (and will take a look at those evictions). Locally I seem to have a full set of published dependencies for M3 and RC1 (with these changes:

- [ ] Natchez PR: https://github.com/tpolecat/natchez/pull/272
- [ ] SourcePos PR: https://github.com/tpolecat/SourcePos/pull/1
- [x] Scodec Cats PR https://github.com/scodec/scodec-cats/pull/17
- [ ] _optional_: Http4s winding fs2/CE forward: https://github.com/http4s/http4s/pull/4471

The jenga is almost complete, I might be able to test my stuff locally with CE3 after all :tada:

**Comment by keynmol** [comment]
The eviction checks are truly a nightmare :D Doesn't work with Scala 3 using 2.13's library... Plus scala-xml dependency from 2.12 is causing issues.

Either way - I've updated this branch (as it doesn't have timeouts, which is what Rob wants I think) to latest versions of things: https://github.com/mpilquist/skunk/compare/topic/fs2-network-refactor...keynmol:fs-latest?expand=1, fixed compilation and removed some bounds found by 2.13.5 (:tada:)

I'd love to know if I can help consolidate those 3 branches into one. I already published skunk from this branch locally and it seems to work, or it may be me not doing anything spectacular with it :)

**Comment by tpolecat** [comment]
Ah shit I have been working on this on my own branch. I will check out what you have done but I'm closing this now to avoid more confusion.

**Pull request closed without merging**
